/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.JsonStudyParamsDAO;
import Outils.Check;
import com.JehodFactory.overviewerss.Params;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import style.GraphicCharter;
import view.generikForms.ButtonCancel;
import view.generikForms.ButtonGenerik;
import view.generikForms.ButtonRefresh;
import view.generikForms.FenGenerik;
import view.generikForms.LabelGenerik;

/**
 *
 * @author nrochas
 */
public class FenCreatStudy extends FenGenerik {

    FenSelectStudy prec;
    /**
     * Creates new form FenCreatStudy
     * @param prec fenetre precedente
     */
    public FenCreatStudy(FenSelectStudy prec) {
        
        this.prec= prec;
        
        Dimension dim = this.getToolkit().getScreenSize();

        initComponents();

        this.setLocation(dim.width / 2 - this.getWidth() / 2, dim.height / 2 - this.getHeight() / 2);
        this.setSize(700, 400);
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabTitre = new LabelGenerik();
        panLabel = new javax.swing.JPanel();
        labname = new LabelGenerik();
        labtrad = new LabelGenerik();
        labPathSvnDoc = new LabelGenerik();
        labfont = new LabelGenerik();
        labPathSvnDel = new LabelGenerik();
        labTabler1 = new LabelGenerik();
        txtfstudyname = new javax.swing.JTextField();
        txtfTrad = new javax.swing.JTextField();
        txtfTAblet = new javax.swing.JTextField();
        cBxFont = new javax.swing.JCheckBox();
        txtfPathSvnDoc = new javax.swing.JTextField();
        txtfsPathSvnDel = new javax.swing.JTextField();
        butcreate = new ButtonGenerik();
        butCancel = new ButtonCancel();
        butrefresh = new ButtonRefresh();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabTitre.setFont(style.GraphicCharter.titre1);
        LabTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabTitre.setText("Create Study");

        labname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labname.setText("Study Name:   ");

        labtrad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labtrad.setText("Traductor:  ");

        labPathSvnDoc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labPathSvnDoc.setText("Path Svn Doc:  ");
        labPathSvnDoc.setToolTipText("");

        labfont.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labfont.setText("Font:  ");

        labPathSvnDel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labPathSvnDel.setText("Path Svn Del:  ");

        labTabler1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labTabler1.setText("Tablet Model:  ");

        txtfstudyname.setFont(GraphicCharter.fontCorps);

        txtfTrad.setFont(GraphicCharter.fontCorps);

        txtfTAblet.setFont(GraphicCharter.fontCorps);

        cBxFont.setText("Samsung Sans");

        txtfPathSvnDoc.setFont(GraphicCharter.fontCorps);

        txtfsPathSvnDel.setFont(GraphicCharter.fontCorps);

        javax.swing.GroupLayout panLabelLayout = new javax.swing.GroupLayout(panLabel);
        panLabel.setLayout(panLabelLayout);
        panLabelLayout.setHorizontalGroup(
            panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLabelLayout.createSequentialGroup()
                .addGroup(panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panLabelLayout.createSequentialGroup()
                        .addGroup(panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labPathSvnDel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(labPathSvnDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                .addComponent(labfont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfPathSvnDoc, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLabelLayout.createSequentialGroup()
                                .addComponent(cBxFont, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(129, 129, 129))
                            .addComponent(txtfsPathSvnDel)))
                    .addGroup(panLabelLayout.createSequentialGroup()
                        .addGroup(panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLabelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labTabler1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labtrad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfTrad)
                            .addComponent(txtfstudyname)
                            .addComponent(txtfTAblet))))
                .addContainerGap())
        );
        panLabelLayout.setVerticalGroup(
            panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labname)
                    .addComponent(txtfstudyname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labtrad)
                    .addComponent(txtfTrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTabler1)
                    .addComponent(txtfTAblet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labfont)
                    .addComponent(cBxFont))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labPathSvnDoc)
                    .addComponent(txtfPathSvnDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labPathSvnDel)
                    .addComponent(txtfsPathSvnDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        butcreate.setText("Create Study");
        butcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butcreateActionPerformed(evt);
            }
        });

        butCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelActionPerformed(evt);
            }
        });

        butrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh1.png"))); // NOI18N
        butrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butrefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LabTitre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(butCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butcreate)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addComponent(panLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butrefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butcreate)
                    .addComponent(butCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butcreateActionPerformed

        Boolean bob;

        String name = txtfstudyname.getText().trim().toUpperCase();
        String trad = txtfTrad.getText().trim().toUpperCase();
        String tablet = txtfTAblet.getText().trim().toUpperCase();
        String pathSvnDoc = txtfPathSvnDoc.getText().trim();
        String pathSvnDel = txtfsPathSvnDel.getText().trim();
        Boolean font = cBxFont.isSelected();

        if (Outils.Check.isGood(name) && Check.isGood(trad) && Check.isGood(tablet)
                && Check.isGood(pathSvnDoc) && Check.isGood(pathSvnDel)) {
            JsonStudyParamsDAO jsp = new JsonStudyParamsDAO();
            bob = jsp.createStudy(name, trad, tablet, font, pathSvnDoc, pathSvnDel);
            
            if (bob) {
                
                Params.getInstance().setStudyName(name);
                Params.getInstance().accedeStudy(name);
                FenStudy fen = new FenStudy(prec);
                this.setVisible(false);
                
            } else {
                JOptionPane.showMessageDialog(null, "Probleme lors de l'enregistrement de la study", "Error", ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tout les champs", "Error", ERROR_MESSAGE);
        }

    }//GEN-LAST:event_butcreateActionPerformed

    private void butCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelActionPerformed
        prec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_butCancelActionPerformed

    private void butrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butrefreshActionPerformed
        
        FenCreatStudy fc = new FenCreatStudy(prec);
        this.dispose();
    }//GEN-LAST:event_butrefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabTitre;
    private javax.swing.JButton butCancel;
    private javax.swing.JButton butcreate;
    private javax.swing.JButton butrefresh;
    private javax.swing.JCheckBox cBxFont;
    private javax.swing.JLabel labPathSvnDel;
    private javax.swing.JLabel labPathSvnDoc;
    private javax.swing.JLabel labTabler1;
    private javax.swing.JLabel labfont;
    private javax.swing.JLabel labname;
    private javax.swing.JLabel labtrad;
    private javax.swing.JPanel panLabel;
    private javax.swing.JTextField txtfPathSvnDoc;
    private javax.swing.JTextField txtfTAblet;
    private javax.swing.JTextField txtfTrad;
    private javax.swing.JTextField txtfsPathSvnDel;
    private javax.swing.JTextField txtfstudyname;
    // End of variables declaration//GEN-END:variables
}
