/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.JsonStudyParamsDAO;
import Outils.Check;
import com.JehodFactory.overviewerss.Params;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import style.GraphicCharter;
import view.generikForms.ButtonCancel;
import view.generikForms.ButtonGenerik;
import view.generikForms.ButtonRefresh;
import view.generikForms.FenGenerik;
import view.generikForms.LabelGenerik;
import view.generikForms.PanBackGenerik;
import view.generikForms.PanGenerik;

/**
 *
 * @author nrochas
 */
public class FenCreatStudy extends FenGenerik {

    FenSelectStudy prec;
    /**
     * Creates new form FenCreatStudy
     * @param prec fenetre precedente
     */
    public FenCreatStudy(FenSelectStudy prec) {
        
        this.prec= prec;
        
        Dimension dim = this.getToolkit().getScreenSize();

        initComponents();

        this.setLocation(dim.width / 2 - this.getWidth() / 2, dim.height / 2 - this.getHeight() / 2);
        //this.setSize(450, 400);
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new PanBackGenerik();
        LabTitre = new LabelGenerik();
        jPanel1 = new javax.swing.JPanel();
        butrefresh = new ButtonRefresh();
        butCancel = new ButtonCancel();
        butcreate = new ButtonGenerik();
        panLabel = new PanGenerik();
        labname = new LabelGenerik();
        labtrad = new LabelGenerik();
        labPathSvnDoc = new LabelGenerik();
        labfont = new LabelGenerik();
        labPathSvnDel = new LabelGenerik();
        labTabler1 = new LabelGenerik();
        txtfstudyname = new javax.swing.JTextField();
        txtfTrad = new javax.swing.JTextField();
        txtfTAblet = new javax.swing.JTextField();
        cBxFont = new javax.swing.JCheckBox();
        txtfPathSvnDoc = new javax.swing.JTextField();
        txtfsPathSvnDel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create Study");

        LabTitre.setBackground(GraphicCharter.colorBlue);
        LabTitre.setFont(style.GraphicCharter.titre1);
        LabTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabTitre.setText("Create Study");
        LabTitre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LabTitre.setOpaque(true);

        jPanel1.setBackground(GraphicCharter.colorYellow);

        butrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh1.png"))); // NOI18N
        butrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butrefreshActionPerformed(evt);
            }
        });

        butCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelActionPerformed(evt);
            }
        });

        butcreate.setText("Create Study");
        butcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butcreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butcreate)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butrefresh)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(butCancel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(butcreate, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap())
        );

        labname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labname.setText("Study Name:   ");

        labtrad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labtrad.setText("Traductor:  ");

        labPathSvnDoc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labPathSvnDoc.setText("Path Svn Doc:  ");
        labPathSvnDoc.setToolTipText("Must be an opening upond Scripts and Settings directories");

        labfont.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labfont.setText("Font:  ");

        labPathSvnDel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labPathSvnDel.setText("Path Svn Del:  ");
        labPathSvnDel.setToolTipText("Must be an opneing upon 1-Finals and 2-Screenshots directories");

        labTabler1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labTabler1.setText("Tablet Model:  ");

        txtfstudyname.setFont(GraphicCharter.fontCorps);
        txtfstudyname.setToolTipText("complete name");

        txtfTrad.setFont(GraphicCharter.fontCorps);
        txtfTrad.setToolTipText("Rws, Mapi, ...");

        txtfTAblet.setFont(GraphicCharter.fontCorps);
        txtfTAblet.setToolTipText("model , size");

        cBxFont.setBackground(panLabel.getBackground());
        cBxFont.setText("Samsung Sans");

        txtfPathSvnDoc.setFont(GraphicCharter.fontCorps);
        txtfPathSvnDoc.setToolTipText("ex: svn://document.kayentis.fr:15000/kayentis/Documentation/Projets/Santé/<CLIENT>/<PROJET>/3- Functional scope/2- Forms/2- Kayentis design/2 – Screenshots/ ");

        txtfsPathSvnDel.setFont(GraphicCharter.fontCorps);
        txtfsPathSvnDel.setToolTipText("svn://svn.kayentis.fr:14000/Kayentis/<CLIENT>/<PROJET>/Platforms/Trunk/ ");

        javax.swing.GroupLayout panLabelLayout = new javax.swing.GroupLayout(panLabel);
        panLabel.setLayout(panLabelLayout);
        panLabelLayout.setHorizontalGroup(
            panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLabelLayout.createSequentialGroup()
                .addGroup(panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panLabelLayout.createSequentialGroup()
                        .addGroup(panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labPathSvnDel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(labPathSvnDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                .addComponent(labfont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtfPathSvnDoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                .addComponent(txtfsPathSvnDel))
                            .addComponent(cBxFont, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panLabelLayout.createSequentialGroup()
                        .addGroup(panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLabelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labTabler1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labtrad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfTrad)
                            .addComponent(txtfstudyname)
                            .addComponent(txtfTAblet))))
                .addContainerGap())
        );
        panLabelLayout.setVerticalGroup(
            panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labname)
                    .addComponent(txtfstudyname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labtrad)
                    .addComponent(txtfTrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTabler1)
                    .addComponent(txtfTAblet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labfont)
                    .addComponent(cBxFont))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labPathSvnDoc)
                    .addComponent(txtfPathSvnDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labPathSvnDel)
                    .addComponent(txtfsPathSvnDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabTitre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butcreateActionPerformed

        Boolean bob;

        String name = txtfstudyname.getText().trim().toUpperCase();
        String trad = txtfTrad.getText().trim().toUpperCase();
        String tablet = txtfTAblet.getText().trim().toUpperCase();
        String pathSvnDoc = Check.autoSlash(txtfPathSvnDoc.getText().trim());
        String pathSvnDel = Check.autoSlash(txtfsPathSvnDel.getText().trim());
        Boolean font = cBxFont.isSelected();

        if (Outils.Check.isGood(name) && Check.isGood(trad) && Check.isGood(tablet)
                && Check.isGood(pathSvnDoc) && Check.isGood(pathSvnDel)) {
            JsonStudyParamsDAO jsp = new JsonStudyParamsDAO();
           if(jsp.createStudy(name, trad, tablet, font, pathSvnDoc, pathSvnDel))           
             {              
                Params.getInstance().setStudyName(name);
                Params.getInstance().accedeStudy(name);
                JOptionPane.showMessageDialog(null, "Study Create","Confirmation creation",INFORMATION_MESSAGE);
                FenStudy fen = new FenStudy(prec);
                this.setVisible(false);
                
            } else {
                JOptionPane.showMessageDialog(null, "Probleme lors de l'enregistrement de la study", "Error", ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tout les champs", "Error", ERROR_MESSAGE);
        }

    }//GEN-LAST:event_butcreateActionPerformed

    private void butCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelActionPerformed
        prec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_butCancelActionPerformed

    private void butrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butrefreshActionPerformed
        
        FenCreatStudy fc = new FenCreatStudy(prec);
        this.dispose();
    }//GEN-LAST:event_butrefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabTitre;
    private javax.swing.JButton butCancel;
    private javax.swing.JButton butcreate;
    private javax.swing.JButton butrefresh;
    private javax.swing.JCheckBox cBxFont;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labPathSvnDel;
    private javax.swing.JLabel labPathSvnDoc;
    private javax.swing.JLabel labTabler1;
    private javax.swing.JLabel labfont;
    private javax.swing.JLabel labname;
    private javax.swing.JLabel labtrad;
    private javax.swing.JPanel panLabel;
    private javax.swing.JTextField txtfPathSvnDoc;
    private javax.swing.JTextField txtfTAblet;
    private javax.swing.JTextField txtfTrad;
    private javax.swing.JTextField txtfsPathSvnDel;
    private javax.swing.JTextField txtfstudyname;
    // End of variables declaration//GEN-END:variables
}
