/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.generikForms.ButtonGenerik;
import java.awt.Dimension;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author nik
 */
public class FenMain extends JFrame
{

    /**
     * Creates new form FenMain
     */
    public FenMain()
    {

        Dimension dim = this.getToolkit().getScreenSize();

        initComponents();

        this.setLocation(dim.width / 2 - this.getWidth() / 2, dim.height / 2 - this.getHeight() / 2);
        this.setSize(478, 400);
        this.setVisible(true);
        pathLabelTxtField.setText("/Settings/Labels");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        labelTitre = new javax.swing.JLabel();
        Labinvite = new javax.swing.JLabel();
        txtFieldPath = new javax.swing.JTextField();
        Labtitle2 = new javax.swing.JLabel();
        pathLabelTxtField = new javax.swing.JTextField();
        butLaunch = new ButtonGenerik();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitre.setFont(style.GraphicCharter.titre1);
        labelTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zone-gd-Lionne-3.jpg"))); // NOI18N
        labelTitre.setToolTipText("");

        Labinvite.setFont(style.GraphicCharter.titre2);
        Labinvite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Labinvite.setText("Copy absolute path of file wich contains file 'Settings'");
        Labinvite.setToolTipText("");

        txtFieldPath.setFont(style.GraphicCharter.fontCorps);
        txtFieldPath.setToolTipText("example: D:/project/CAIN457M2302/trunk");

        Labtitle2.setFont(style.GraphicCharter.titre2);
        Labtitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Labtitle2.setText("Path of labels file");
        Labtitle2.setToolTipText("ce path arrive a la suite du premier");

        pathLabelTxtField.setFont(style.GraphicCharter.fontCorps);
        pathLabelTxtField.setToolTipText("Edit if necessary");

        butLaunch.setText("Tracking");
        butLaunch.setToolTipText("");
        butLaunch.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                butLaunchActionPerformed(evt);
            }
        });

        jLabel1.setFont(style.GraphicCharter.fontCorps);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Apres le lancement, attendre l'apparition de la fenetre de fin.");
        jLabel1.setToolTipText("Si elle apparait pas dans les 30 sec ce que ca a dû planter");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(txtFieldPath, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(pathLabelTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(butLaunch)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Labtitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Labinvite, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Labinvite, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Labtitle2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pathLabelTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butLaunch)
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butLaunchActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_butLaunchActionPerformed
    {//GEN-HEADEREND:event_butLaunchActionPerformed
        String path;
        String pathLabels;

        if (txtFieldPath.getText() == null || pathLabelTxtField.getText() == null || txtFieldPath.getText().trim().equals("") || txtFieldPath.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Remplissez tout les champs svp", "Error Fill Field", JOptionPane.ERROR_MESSAGE, new ImageIcon("/rugissment.png"));
        } else if (txtFieldPath.getText().endsWith("/") || !pathLabelTxtField.getText().startsWith("/"))
        {
            JOptionPane.showMessageDialog(null, "le path ne doit pas finir par un slash et le path labels doit commencer par un slash", "Error Fill Field", JOptionPane.ERROR_MESSAGE, 
                    new ImageIcon("/rugissment.png"));
        } else
        {
            path = txtFieldPath.getText();
            pathLabels = pathLabelTxtField.getText();

            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Confirmez l'adresse saisie:" + path + pathLabels, "confirmation", dialogButton);

            if (dialogResult == JOptionPane.YES_OPTION)
            {
                this.dispose();
                FenProgress fenp = new FenProgress();
                fenp.setVisible(true);
                metier.OverView ov = new metier.OverView(path, pathLabels, true);
                ov.overview(fenp);
            } else
            {
                System.out.println("lpol");
            }

        }


    }//GEN-LAST:event_butLaunchActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Labinvite;
    private javax.swing.JLabel Labtitle2;
    private javax.swing.JButton butLaunch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelTitre;
    private javax.swing.JTextField pathLabelTxtField;
    private javax.swing.JTextField txtFieldPath;
    // End of variables declaration//GEN-END:variables
}
