/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.JsonStudyParamsDAO;
import Outils.Check;
import view.generikForms.FenGenerik;
import view.generikForms.ButtonGenerik;
import com.JehodFactory.overviewerss.Params;
import entity.SimpleStudyParam;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import model.ComboModel;
import style.GraphicCharter;
import view.generikForms.ButtonCancel;
import view.generikForms.ButtonRefresh;

/**
 *
 * @author nrochas
 */
public class FenStudy extends FenGenerik {

    String studyName = Params.getInstance().studyName;
    SimpleStudyParam ssp = Params.getInstance().studyParam;
    ArrayList<String> list = ssp.getListStudyPath();

    String studyPath;
    String pathSvnDel = ssp.getPathSvnDel();
    String pathSvnDoc = ssp.getPathSvnDoc();

    FenSelectStudy prec;

    /**
     * Creates new form FenStudy
     */
    public FenStudy(FenSelectStudy fss) {

        //on note la fenetre d'avant pour le retour arriere
        prec = fss;
        Dimension dim = this.getToolkit().getScreenSize();

        initComponents();

        this.setLocation(dim.width / 2 - this.getWidth() / 2, dim.height / 2 - this.getHeight() / 2);
        this.setSize(478, 400);
        this.setVisible(true);
        //on cache le browser
        butSelect.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboStudyPath = new javax.swing.JComboBox<>();
        butLaunchSVN = new ButtonGenerik();
        butAddPath = new ButtonGenerik();
        butSelect = new javax.swing.JFileChooser();
        butViewStudy = new ButtonGenerik();
        butCancel = new ButtonCancel();
        jButton1 = new ButtonRefresh();
        butLaunchLocal = new ButtonGenerik();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(style.GraphicCharter.titre1);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(studyName);

        jLabel6.setFont(GraphicCharter.titre3);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Path for Local Track:  ");
        jLabel6.setToolTipText("");

        comboStudyPath.setFont(GraphicCharter.titre3
        );
        comboStudyPath.setMaximumRowCount(10);
        comboStudyPath.setModel(new ComboModel(list));

        butLaunchSVN.setText("Track SVN");
        butLaunchSVN.setToolTipText("Use SVN1400 and SVN1500. Put no file in local depositoy");
        butLaunchSVN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLaunchSVNActionPerformed(evt);
            }
        });

        butAddPath.setText("...");
        butAddPath.setToolTipText("Browser");
        butAddPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAddPathActionPerformed(evt);
            }
        });

        butSelect.setApproveButtonText("Select");
        butSelect.setApproveButtonToolTipText("");
        butSelect.setCurrentDirectory(new java.io.File("C:\\"));
            butSelect.setDialogTitle("");
            butSelect.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
            butSelect.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    butSelectActionPerformed(evt);
                }
            });

            butViewStudy.setText("View Study Details");
            butViewStudy.setToolTipText("Give some details and possibility of modification ");
            butViewStudy.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    butViewStudyActionPerformed(evt);
                }
            });

            butCancel.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    butCancelActionPerformed(evt);
                }
            });

            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh1.png"))); // NOI18N
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            butLaunchLocal.setText("Track Local");
            butLaunchLocal.setToolTipText("Analysis of local work. No contact with Svn");
            butLaunchLocal.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    butLaunchLocalActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 3, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(17, 17, 17))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(butCancel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(butViewStudy)
                            .addGap(26, 26, 26))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(comboStudyPath, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(butAddPath, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(butLaunchSVN)
                                        .addComponent(butLaunchLocal))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGap(18, 18, 18)))
                    .addComponent(butSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(21, 21, 21))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jButton1)))
                            .addGap(56, 56, 56)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(comboStudyPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(butAddPath))
                            .addGap(41, 41, 41)
                            .addComponent(butLaunchLocal)
                            .addGap(29, 29, 29)
                            .addComponent(butLaunchSVN)
                            .addGap(37, 37, 37)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(butCancel)
                                .addComponent(butViewStudy))
                            .addGap(0, 104, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(butSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addContainerGap())
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void butLaunchSVNActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_butLaunchSVNActionPerformed
    {//GEN-HEADEREND:event_butLaunchSVNActionPerformed

        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Confirm complete path:" + pathSvnDel + " \r This method put nothing in local. Please update your working copy after.", "confirmation", dialogButton);

        if (dialogResult == JOptionPane.YES_OPTION) {
            Params.getInstance().setStudyPath(pathSvnDel);

            this.dispose();
            FenProgress fenp = new FenProgress();
            fenp.setVisible(true);
            metier.OverView ov = new metier.OverView(pathSvnDel, false);
            ov.overview();

        }

    }//GEN-LAST:event_butLaunchSVNActionPerformed

    private void butAddPathActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_butAddPathActionPerformed
    {//GEN-HEADEREND:event_butAddPathActionPerformed
        String select;
        butSelect.setVisible(true);
        //this.setSize(1000, 400);
        int retour = butSelect.showOpenDialog(this);
        if (retour == JFileChooser.APPROVE_OPTION) {
            select = butSelect.getSelectedFile().getAbsolutePath();
            System.out.println("select: " + select);
            //this.setSize(500,400);
            if (!Check.checkIsIn(select, list)) {
                list.add(select);
            }
            comboStudyPath.setSelectedItem(select);
            comboStudyPath.repaint();
        }
    }//GEN-LAST:event_butAddPathActionPerformed

    private void butSelectActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_butSelectActionPerformed
    {//GEN-HEADEREND:event_butSelectActionPerformed


    }//GEN-LAST:event_butSelectActionPerformed

    private void butViewStudyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butViewStudyActionPerformed
        FenViewStudy fw = new FenViewStudy(this);
        this.setVisible(false);
    }//GEN-LAST:event_butViewStudyActionPerformed

    private void butCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelActionPerformed
        prec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_butCancelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        FenStudy fs = new FenStudy(prec);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void butLaunchLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLaunchLocalActionPerformed

        studyPath = (String) comboStudyPath.getSelectedItem();

        if (!Check.isGood(studyPath)) {
            JOptionPane.showMessageDialog(null, "PLease select a study ", "Error Filling conboBox", ERROR_MESSAGE);
            comboStudyPath.setBackground(Color.red);
            comboStudyPath.repaint();
        } else {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Confirm complete path:" + studyPath + " \r  This method has no contact with svn. Please commit after.", "confirmation", dialogButton);
           
            if (dialogResult == JOptionPane.YES_OPTION) {
                Params.getInstance().setStudyPath(studyPath);

                this.dispose();
                FenProgress fenp = new FenProgress();
                fenp.setVisible(true);
                metier.OverView ov = new metier.OverView(studyPath, true);
                ov.overview();
            }
        }
    }//GEN-LAST:event_butLaunchLocalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAddPath;
    private javax.swing.JButton butCancel;
    private javax.swing.JButton butLaunchLocal;
    private javax.swing.JButton butLaunchSVN;
    private javax.swing.JFileChooser butSelect;
    private javax.swing.JButton butViewStudy;
    private javax.swing.JComboBox<String> comboStudyPath;
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
