/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.JsonStudyParamsDAO;
import Outils.Check;
import com.JehodFactory.overviewerss.Params;
import entity.SimpleStudyParam;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import style.GraphicCharter;
import view.generikForms.ButtonCancel;
import view.generikForms.ButtonGenerik;
import view.generikForms.ButtonRefresh;
import view.generikForms.LabelGenerik;
import view.generikForms.PanBackGenerik;
import view.generikForms.PanGenerik;

/**
 *
 * @author nrochas
 */
public class FenViewStudy extends javax.swing.JFrame {

    String pathSvnDoc;
    String pathSvnDel;

    String trad;
    String tabletModel;
    boolean font;
    String studyName = Params.getInstance().studyName;
    SimpleStudyParam ssp = Params.getInstance().studyParam;
    ArrayList<String> list = ssp.getListStudyPath();
    FenStudy prec;

    /**
     * Creates new form FenViewStudy
     * @param prec
     */
    public FenViewStudy(JFrame prec) {
        Dimension dim = this.getToolkit().getScreenSize();
        this.prec = (FenStudy) prec;
        initComponents();

        this.setLocation(dim.width / 2 - this.getWidth() / 2, dim.height / 2 - this.getHeight() / 2);
        //this.setSize(800, 400);
        this.setResizable(true);
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panFond = new PanBackGenerik();
        panOfFiels = new PanGenerik();
        TxtFieldPathSvnDel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtFieldPathSvnDoc = new javax.swing.JTextField();
        labfont = new LabelGenerik();
        TxtFieldTabModel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtFieldTrad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cBxFont = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        butCancel = new ButtonCancel();
        butrefresh = new ButtonRefresh();
        buttSaveNGo = new ButtonGenerik();
        butMap = new ButtonGenerik();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Study");

        TxtFieldPathSvnDel.setFont(GraphicCharter.titre3);
        TxtFieldPathSvnDel.setText(ssp.getPathSvnDel());
        TxtFieldPathSvnDel.setToolTipText("path on svn14000");

        jLabel2.setFont(GraphicCharter.titre3);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Tablet Models:  ");
        jLabel2.setToolTipText("");

        TxtFieldPathSvnDoc.setFont(GraphicCharter.titre3);
        TxtFieldPathSvnDoc.setText(ssp.getPathSvnDoc());
        TxtFieldPathSvnDoc.setToolTipText("path on svn15000");
        TxtFieldPathSvnDoc.setMaximumSize(new java.awt.Dimension(72, 20));
        TxtFieldPathSvnDoc.setMinimumSize(new java.awt.Dimension(72, 20));

        labfont.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labfont.setText("Font:  ");

        TxtFieldTabModel.setFont(GraphicCharter.titre3);
        TxtFieldTabModel.setText(ssp.getTabModel());

        jLabel4.setFont(GraphicCharter.titre3);
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Path Svn Del:  ");
        jLabel4.setToolTipText("");

        TxtFieldTrad.setFont(GraphicCharter.titre3);
        TxtFieldTrad.setText(ssp.getTrad());
        TxtFieldTrad.setToolTipText("");

        jLabel3.setFont(GraphicCharter.titre3);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Path Svn Doc:  ");

        cBxFont.setBackground(panOfFiels.getBackground());
        cBxFont.setSelected(ssp.getFontSamsung());
        cBxFont.setText("Samsung Sans");

        jLabel5.setFont(GraphicCharter.titre3);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Traductor:  ");

        javax.swing.GroupLayout panOfFielsLayout = new javax.swing.GroupLayout(panOfFiels);
        panOfFiels.setLayout(panOfFielsLayout);
        panOfFielsLayout.setHorizontalGroup(
            panOfFielsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panOfFielsLayout.createSequentialGroup()
                .addGroup(panOfFielsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panOfFielsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panOfFielsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labfont, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panOfFielsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtFieldPathSvnDel)
                    .addComponent(TxtFieldTabModel)
                    .addComponent(cBxFont, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                    .addComponent(TxtFieldTrad)
                    .addComponent(TxtFieldPathSvnDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panOfFielsLayout.setVerticalGroup(
            panOfFielsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOfFielsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panOfFielsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtFieldPathSvnDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panOfFielsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtFieldPathSvnDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panOfFielsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtFieldTrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panOfFielsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtFieldTabModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panOfFielsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labfont)
                    .addComponent(cBxFont))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel1.setBackground(style.GraphicCharter.colorBlue);
        jLabel1.setFont(style.GraphicCharter.titre1);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(studyName);
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setOpaque(true);

        jPanel2.setBackground(GraphicCharter.colorYellow);

        butCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelActionPerformed(evt);
            }
        });

        butrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh1.png"))); // NOI18N
        butrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butrefreshActionPerformed(evt);
            }
        });

        buttSaveNGo.setText("Save n Go");
        buttSaveNGo.setToolTipText("save modification");
        buttSaveNGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttSaveNGoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addComponent(butrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(buttSaveNGo)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(butCancel)
                        .addComponent(buttSaveNGo))
                    .addComponent(butrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        butMap.setText("Mapping");
        butMap.setToolTipText("create mapping between screenshot and label names");
        butMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butMapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panFondLayout = new javax.swing.GroupLayout(panFond);
        panFond.setLayout(panFondLayout);
        panFondLayout.setHorizontalGroup(
            panFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panOfFiels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panFondLayout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(butMap)
                .addGap(246, 246, 246))
        );
        panFondLayout.setVerticalGroup(
            panFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(panOfFiels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(butMap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFond, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFond, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butrefreshActionPerformed
        FenViewStudy fs = new FenViewStudy(prec);
        this.dispose();
    }//GEN-LAST:event_butrefreshActionPerformed

    private void butCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelActionPerformed
        this.dispose();
        prec.setVisible(true);
    }//GEN-LAST:event_butCancelActionPerformed

    private void buttSaveNGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttSaveNGoActionPerformed
        JsonStudyParamsDAO jspd = new JsonStudyParamsDAO();    

        if (!recupInfo()) {
            JOptionPane.showMessageDialog(null, "Please dont left an empty field", "Missing fields", JOptionPane.ERROR_MESSAGE);
        }  else {               

            if (jspd.modifStudy(studyName, trad, tabletModel, font, pathSvnDoc, pathSvnDel)) {
                JOptionPane.showMessageDialog(null, "Data saved", "Confirmation", INFORMATION_MESSAGE);
                //sauvegarde dans la VM
               
                Params.getInstance().accedeStudy(studyName);
            } else {
                JOptionPane.showMessageDialog(null, "A problems occured", "Save failed", JOptionPane.ERROR_MESSAGE);
            }
            
            
            this.dispose();
            if (prec.getClass().getSimpleName().equals("FenStudy")){ prec.refresh();}
           

        }
    }//GEN-LAST:event_buttSaveNGoActionPerformed

    private void butMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butMapActionPerformed
        FenMapping fm = new FenMapping(this);
        this.setVisible(false);
    }//GEN-LAST:event_butMapActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtFieldPathSvnDel;
    private javax.swing.JTextField TxtFieldPathSvnDoc;
    private javax.swing.JTextField TxtFieldTabModel;
    private javax.swing.JTextField TxtFieldTrad;
    private javax.swing.JButton butCancel;
    private javax.swing.JButton butMap;
    private javax.swing.JButton butrefresh;
    private javax.swing.JButton buttSaveNGo;
    private javax.swing.JCheckBox cBxFont;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labfont;
    private javax.swing.JPanel panFond;
    private javax.swing.JPanel panOfFiels;
    // End of variables declaration//GEN-END:variables

    private boolean recupInfo() {
       
        pathSvnDel = Check.autoSlash(TxtFieldPathSvnDel.getText());
        pathSvnDoc = Check.autoSlash(TxtFieldPathSvnDoc.getText());
        trad = TxtFieldTrad.getText();
        tabletModel = TxtFieldTabModel.getText();
        font = cBxFont.isSelected();

        return (Check.isGood(pathSvnDel) && Check.isGood(pathSvnDoc) && Check.isGood(trad) && Check.isGood(tabletModel));
    }

  

}
