/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.JsonStudyParamsDAO;
import Outils.Check;
import com.JehodFactory.overviewerss.Params;
import entity.SimpleStudyParam;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import style.GraphicCharter;
import view.generikForms.ButtonCancel;
import view.generikForms.ButtonGenerik;
import view.generikForms.ButtonRefresh;
import view.generikForms.LabelGenerik;

/**
 *
 * @author nrochas
 */
public class FenViewStudy extends javax.swing.JFrame {

    String pathSvnDoc;
    String pathSvnDel;

    String trad;
    String tabletModel;
    boolean font;
    String studyName = Params.getInstance().studyName;
    SimpleStudyParam ssp = Params.getInstance().studyParam;
    ArrayList<String> list = ssp.getListStudyPath();
    JFrame prec;

    /**
     * Creates new form FenViewStudy
     */
    public FenViewStudy(JFrame prec) {
        Dimension dim = this.getToolkit().getScreenSize();
        this.prec = prec;
        initComponents();

        this.setLocation(dim.width / 2 - this.getWidth() / 2, dim.height / 2 - this.getHeight() / 2);
        this.setSize(478, 400);
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtFieldPathSvnDoc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtFieldPathSvnDel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtFieldTrad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtFieldTabModel = new javax.swing.JTextField();
        butrefresh = new ButtonRefresh();
        jLabel3 = new javax.swing.JLabel();
        butCancel = new ButtonCancel();
        buttSaveNGo = new ButtonGenerik();
        cBxFont = new javax.swing.JCheckBox();
        labfont = new LabelGenerik();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TxtFieldPathSvnDoc.setFont(GraphicCharter.titre3);
        TxtFieldPathSvnDoc.setText(ssp.getPathSvnDoc());

        jLabel4.setFont(GraphicCharter.titre3);
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Path Svn Del:  ");
        jLabel4.setToolTipText("");

        TxtFieldPathSvnDel.setFont(GraphicCharter.titre3);
        TxtFieldPathSvnDel.setText(ssp.getPathSvnDel());

        jLabel5.setFont(GraphicCharter.titre3);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Traductor:  ");

        TxtFieldTrad.setFont(GraphicCharter.titre3);
        TxtFieldTrad.setText(ssp.getTrad());

        jLabel1.setFont(style.GraphicCharter.titre1);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(studyName);

        jLabel2.setFont(GraphicCharter.titre3);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Tablet Models:  ");
        jLabel2.setToolTipText("");

        TxtFieldTabModel.setFont(GraphicCharter.titre3);
        TxtFieldTabModel.setText(ssp.getTabModel());

        butrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh1.png"))); // NOI18N
        butrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butrefreshActionPerformed(evt);
            }
        });

        jLabel3.setFont(GraphicCharter.titre3);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Path Svn Doc:  ");

        butCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelActionPerformed(evt);
            }
        });

        buttSaveNGo.setText("Save n Go");
        buttSaveNGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttSaveNGoActionPerformed(evt);
            }
        });

        cBxFont.setText("Samsung Sans");

        labfont.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labfont.setText("Font:  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(butCancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttSaveNGo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtFieldPathSvnDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labfont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cBxFont, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                            .addComponent(TxtFieldPathSvnDel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TxtFieldTabModel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                .addComponent(TxtFieldTrad, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(butrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(258, 258, 258))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtFieldPathSvnDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtFieldPathSvnDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtFieldTrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtFieldTabModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labfont)
                    .addComponent(cBxFont))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butCancel)
                    .addComponent(buttSaveNGo))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butrefreshActionPerformed
        FenViewStudy fs = new FenViewStudy(prec);
        this.dispose();
    }//GEN-LAST:event_butrefreshActionPerformed

    private void butCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelActionPerformed
        this.dispose();
        prec.setVisible(true);
    }//GEN-LAST:event_butCancelActionPerformed

    private void buttSaveNGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttSaveNGoActionPerformed
        JsonStudyParamsDAO jspd = new JsonStudyParamsDAO();;

        if (!recupInfo()) {
            JOptionPane.showMessageDialog(null, "Please dont left an empty field", "Missing fields", JOptionPane.ERROR_MESSAGE);
        }  else {

            
           //if (jspd.modifStudy(studyName, trad, tabletModel, font, pathSvnDoc, pathSvnDel))
          // {JOptionPane.showMessageDialog(null, "Modification done", "Confirmation", INFORMATION_MESSAGE);}
          //else{JOptionPane.showMessageDialog(null, "A problems occured", "Save failed", JOptionPane.ERROR_MESSAGE);}
            this.dispose();
            
        }
    }//GEN-LAST:event_buttSaveNGoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtFieldPathSvnDel;
    private javax.swing.JTextField TxtFieldPathSvnDoc;
    private javax.swing.JTextField TxtFieldTabModel;
    private javax.swing.JTextField TxtFieldTrad;
    private javax.swing.JButton butCancel;
    private javax.swing.JButton butrefresh;
    private javax.swing.JButton buttSaveNGo;
    private javax.swing.JCheckBox cBxFont;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labfont;
    // End of variables declaration//GEN-END:variables

    private boolean recupInfo() {
        pathSvnDel = TxtFieldPathSvnDel.getText();
        pathSvnDoc = TxtFieldPathSvnDoc.getText();
        trad = TxtFieldTrad.getText();
        tabletModel = TxtFieldTabModel.getText();

        return (Check.isGood(pathSvnDel) && Check.isGood(pathSvnDoc) && Check.isGood(trad) && Check.isGood(tabletModel));
    }

}
